### ISSUE TITLE
Metric emission methods in metrics.go modify input key slice

### ISSUE THREAD

**Issue by rturner3** [armon/go-metrics#101]
All the metric emission methods in `Metrics` from metrics.go are checking for the state of certain configuration flags like `EnableHostname`, and if set to true, are modifying the source `key` slice passed as an argument.

See [here](https://github.com/armon/go-metrics/blob/13f9d8e9b41c66738153b7582f1f62add8e407c8/metrics.go#L23) for one such example.

Modification of the input `key` slice causes it to be unusable when emitting it to multiple `Metrics` objects if any configuration flags which cause modification of the input `key` slice are enabled. If different metrics sinks need different configuration, it requires using multiple `Metrics` objects since the config is per-`Metrics` object.

This results in the client being responsible for creating copies of the same `key` slice for each time it emits the metric to different `Metrics` objects, which requires allocating a new `[]string`. This drastically hurts the performance of emitting metrics.

**Comment by rturner3** [comment]
Here is a small example which replicates the issue. Notice how the last two elements of the original slice disappear after calling the method `messWithKey()`.
https://play.golang.org/p/04IUEGSeBJ_7

**Comment by rturner3** [comment]
This is a simpler implementation of `insert()` which does not modify the original slice passed in:
https://play.golang.org/p/AK4GKMCCQ49

**Comment by amoore877** [comment]
> This is a simpler implementation of `insert()` which does not modify the original slice passed in:
> https://play.golang.org/p/AK4GKMCCQ49

Additionally, that implementation takes advantage of the fact that today's [insert](https://github.com/armon/go-metrics/blob/master/metrics.go#L273) function is only called with index 0 (prepend).

The example at https://play.golang.org/p/AK4GKMCCQ49 seems to be the more idiomatic, and safe, way to get a new slice from prepending a single element to an existing one. Crucially it does not modify the existing slice.

Normally perhaps an argument could be made that callers should just pass a copy, but I would argue:
1. Functions should state if they will modify a slice
1. For something like metrics, we should be decreasing memory allocations as much as possible. Metrics should not be something that adds significant overhead to a program.

This proposed solution:
- alleviates callers of extra allocations
- is more performant than existing implementation
- simplifies existing implementation down to only what is actually needed
