### ISSUE TITLE
Question: implication of key flattening in terms of GC and performance

### ISSUE THREAD

**Issue by jondot** [armon/go-metrics#14]
Hi,
I am wondering if the key flattening process on each sink is affecting performance? (since this is a metrics library, it might affect the metrics that it measures itself).

Thanks

**Comment by armon** [comment]
@jondot they are certainly not free, and do have a measurable overhead. In our uses the overhead added by the profiling is minimal compared to the work done to service the requests themselves so it's not an issue. That said, there is probably room to optimize things a bit

**Comment by jondot** [comment]
@armon thanks!, I decided to implement my metrics with your library. Some back of napkin calculations showed that I'd be doing these joins in any case.
