### ISSUE TITLE
Question: composition of metric key in Gauge - host first / last

### ISSUE THREAD

**Issue by jondot** [armon/go-metrics#15]
Hi,
Another question here. I'm used to the host part in metrics being last, e.g.:

```
env.product.category.metric.host
```
Makes the host somewhat insignificant in data slicing, and grouping is an easy `env.product.category.metric.*` which is really true for today's services.

Historically (that is, years ago), I've been inspired by Google's [RockSteady](https://code.google.com/p/rocksteady/wiki/MetricFormat) as guidelines to sculpt my metrics.

So a real key would look like:

```
production.main_api.routes.health.GET.apisrv110
```

However, with `go-metrics` I see that the host comes quite first. Is there something I can learn from this? do you find it better at that position? would love to hear your experience about this.

Thanks

**Comment by armon** [comment]
@jondot It can go in both ways. I tend to think of the key as going from least granularity to most granularity. So the hostname is a very broad granularity. I'm not sure where the origin of this was, I think I must have just gotten used to that approach at some point. In the big picture, its a difference without a distinction.

**Comment by jondot** [comment]
Thanks! I have another question regarding logging but I'll open as a new thread. Hopefully all of these questions and answers can either end up as a Wiki or just live here as close issues for others to enjoy :)
