### ISSUE TITLE
Enhancement: Windowed Sink

### ISSUE THREAD

**Issue by kung-foo** [armon/go-metrics#18]
Hi, I've started working on a windowed version of the `InmemSink`. This allows you to specify a time range where samples are kept. Rather than the fixed interval of `InmemSink`, this is a rolling window where samples expire. Statistics are mostly calculated on demand (rather than at ingestion time). Samples are collected in a fixed size ring buffer and are either overwritten or expired as needed.

Example usage:

``` go
// setup windows for a sample rate of 2Hz
cpu5 := metrics.NewWindowSink(time.Second*5, 10)
cpu15 := metrics.NewWindowSink(time.Second*15, 30)
cpu60 := metrics.NewWindowSink(time.Second*60, 120)

// use fanout sink to write to all three windows
cpuSink := &metrics.FanoutSink{cpu5, cpu15, cpu60}

key := []string{"cpu"}

go func() {
    // collect CPU utilization every 500ms
    for _ = range time.Tick(time.Millisecond * 500) {
        v, _ := cpu.CPUPercent(0, false)
        cpuSink.AddSample(key, float32(v[0]))
    }
}()

// wait for first samples to come in
time.Sleep(time.Second * 1)

for _ = range time.Tick(time.Second * 1) {
    log.Printf("5s: %05.2f%%, 15s: %05.2f%%, 60s: %05.2f%%\n",
        cpu5.Sample(key).Mean(),
        cpu15.Sample(key).Mean(),
        cpu60.Sample(key).Mean())
}
```

I've only implemented `sink.AddSample()` so far, but am interested in your comments.

Current branch: https://github.com/kung-foo/go-metrics/tree/window
- jonathan

**Comment by armon** [comment]
I'm not sure I necessarily see the benefit of this approach. It also requires storing more sample points, where the ingest time-aggregation allows that memory to be reclaimed.

**Comment by kung-foo** [comment]
I agree that the ingest time-aggregation is much more memory efficient. My issue is that the `InmemSink` aggregations are misleading. For example, if I record a sample once a second, with a ten second interval, and the data alternates on a regular basis, I would expect the `mean()` to be constant. In the chart below, I write the value `0.0` for 5 seconds, then `10.0` for 5 seconds and repeat. Asking the `InmemSink` for the `mean()` gives wildly different results depending on when it is run. Versus the `WindowSink` which is constant.

![metrics](https://cloud.githubusercontent.com/assets/1357571/7912610/55d5ee42-0869-11e5-8891-c326bf742cfc.png)

I wouldn't expect people to use a `WindowSink` for long periods with a high sample rate, in that case, the standard `InmemSink` would be sufficient.

Do you see a way to implement the above CPU example (with 5s, 15s, and 60s) using just the `InmemSink`?

Regarding memory reclamation, with the constructor requiring both the window size (`time.Duration`) and a maximum sample count, the memory consumption is bounded.

**Comment by armon** [comment]
@kung-foo The way this library is expected to be used, you only sample at the end of the 10s interval, so the averages would still work out correctly. Either way, this may just be something best implemented outside of this project, as I'd like to keep its scope limited.

**Comment by kung-foo** [comment]
@armon I finally got around to moving it out here: https://github.com/kung-foo/go-metrics-sinks

I also have an expvar based sink, but I assume that you would also like to keep that out of the main lib?
