### ISSUE TITLE
Use of TCP makes this incompatible with StatsD

### ISSUE THREAD

**Issue by blalor** [armon/go-metrics#2]
The exclusive use of TCP for sending metrics to the backend metrics server means this library is incompatible with StatsD.  Therefore Consul is unable to send metrics to StatsD, as it uses this library.  Since statsite itself supports UDP, this library should as well.

**Comment by juliusv** [comment]
Seems like this can be closed, as there is a StatsD sink now?

**Comment by armon** [comment]
Yep!
