### ISSUE TITLE
Would you welcome an HTTP/inmem adapter?

### ISSUE THREAD

**Issue by jondot** [armon/go-metrics#21]
Sort of like what expvar does https://golang.org/pkg/expvar/?
This also raises a design question, I see a pattern here of adapters exposing the same inmem store. It bothers me that it would make the inmem store "blessed" more than others.
What do you think?

**Comment by armon** [comment]
@jondot I think it would be fine, but go metrics is really designed to push metrics and not really retain them.

**Comment by abennett** [comment]
Closing this issue. No further action required.
