### ISSUE TITLE
mutex vs atomic usage

### ISSUE THREAD

**Issue by andrewwebber** [armon/go-metrics#25]
Is it a concern or not that mutexs are used where atomic could be substituted 

rcrowley uses the atomic package for example 
https://github.com/rcrowley/go-metrics/blob/master/gauge.go

https://texlution.com/post/golang-lock-free-values-with-atomic-value/

**Comment by armon** [comment]
@andrewwebber I don't think there is any concern here. There are only a few locks in the entire package and they are not ones that can be trivially replaced with atomics, and their performance has not been a concern so far in Serf, Consul, Nomad or Vault.

**Comment by andrewwebber** [comment]
I haven't reviewed your implementation yet but I'm trying to avoid that a microservice REST endpoint being hammered by a load test would not be spending its time locking perf counters

**Comment by armon** [comment]
@andrewwebber We use it in many production systems at HashiCorp, and some of those systems have been benchmarked at tens of thousands of requests per second, without spending any significant time in the metrics layers during profiling. Hope that helps!
