### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [armon/go-metrics#27]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-metrics and versioning would help Debian keep up with development.

**Comment by armon** [comment]
@aviau Sure, I can tag version releases. Is just a git tag enough?

**Comment by aviau** [comment]
Yes this would be enough! Thank you :)!

**Comment by armon** [comment]
Sounds good, I will tag the future releases

**Comment by onlyjob** [comment]
Tags will be much appreciated. It might be useful to consider semantic versioning: http://semver.org

**Comment by onlyjob** [comment]
There are still no releases...

Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Also compatibility with [gopkg.in](http://labix.org/gopkg.in) (and other tools that vendor by tags) could be useful.

Thank you.

See also

 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by onlyjob** [comment]
Long time passed but there are no tags/releases yet... @armon, could you please re-open this issue?

**Comment by onlyjob** [comment]
Another year passed but there are still no tags... @armon, when would it be possible to have a first formal release?
